{% set version = "2.0.3" %}

package:
  name: fmilib
  version: {{ version }}

source:
  fn: FMILibrary-{{ version }}-src.zip
  url: https://jmodelica.org/FMILibrary/FMILibrary-{{ version }}-src.zip
  sha256: 4cc21f9e2c4114a6f4e303f82ca897ec9aa1eb6f7f09fef85979ea5fca309d9a
  patches:
    # https://github.com/conda/conda-build/issues/3165
    - undef_gnu_source.patch

build:
  number: 1002
  run_exports:
    - {{ pin_subpackage('fmilib', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - test -f $PREFIX/include/fmilib.h                                # [unix]
    - test -f $PREFIX/lib/libfmilib.a                                 # [unix]
    - if not exist %PREFIX%\\Library\\lib\\fmilib.lib exit 1          # [win]
    - if not exist %PREFIX%\\Library\\include\\fmilib.h exit 1        # [win]
    - conda inspect linkages -p ${PREFIX} fmilib  # [not win]
    - conda inspect objects -p ${PREFIX} fmilib  # [osx]

about:
  home: http://www.jmodelica.org/FMILibrary
  license: BSD
  summary: Package written in C that enables integration of Functional Mock-up Units

extra:
  recipe-maintainers:
    - jschueller
