{% set version = "3.0.3" %}

package:
  name: fmilib
  version: {{ version }}

source:
  url: https://github.com/modelon-community/fmi-library/archive/{{ version }}.tar.gz
  sha256: 1acffcd157c2901c5bbccfc848425de0c661eacea24475aff842ef3ba7fb05a6
build:
  number: 0
  run_exports:
    - {{ pin_subpackage('fmilib', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - make  # [unix]
    - gnuconfig  # [unix]
    - ninja  # [win]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - expat
    - zlib
    - minizip

test:
  commands:
    - test -f $PREFIX/include/fmilib.h                                # [unix]
    - test -f $PREFIX/lib/libfmilib.a                                 # [unix]
    - if not exist %PREFIX%\\Library\\lib\\fmilib.lib exit 1          # [win]
    - if not exist %PREFIX%\\Library\\include\\fmilib.h exit 1        # [win]

about:
  home: http://www.jmodelica.org/FMILibrary
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Package written in C that enables integration of Functional Mock-up Units

extra:
  recipe-maintainers:
    - jschueller
