{% set version = "2.4" %}

package:
  name: fmilib
  version: {{ version }}

source:
  url: https://github.com/modelon-community/fmi-library/archive/{{ version }}.tar.gz
  sha256: d77ff7c52ab97d8cc6210cee695091e6e3aab9455448ed867231de5bc32e20e5
  patches:
    # https://github.com/conda/conda-build/issues/3165
    - undef_gnu_source.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('fmilib', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - make  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - test -f $PREFIX/include/fmilib.h                                # [unix]
    - test -f $PREFIX/lib/libfmilib.a                                 # [unix]
    - if not exist %PREFIX%\\Library\\lib\\fmilib.lib exit 1          # [win]
    - if not exist %PREFIX%\\Library\\include\\fmilib.h exit 1        # [win]

about:
  home: http://www.jmodelica.org/FMILibrary
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Package written in C that enables integration of Functional Mock-up Units

extra:
  recipe-maintainers:
    - jschueller
