travis:
  secure:
    BINSTAR_TOKEN: ggs0C2lzA0sT9hzphzK6XllPXkxBxIDgzfxdXDuQJgOb5umOH+Vqxs9CwYmHQG4sXj1WdcB7XVlDtSqifGQMnswHFTorl/u3EB3w0hGjgNDzG8OQqvLB/3A8FimW2IChM2FkRrfMQqt1+V74b1Zu7PTIa8HxEj7ogkzcHdXTP3r0uNRcV4d+WgGfaNC6MSPFfaqNOtp4ehUBEG6Xb1R/8SHOMJe6Xmo9hX9Kz6zBFBzPHpzYDtVIywZgE0fMB2L0p8Kr24j7KPa5CxuJ0IQWUhYA4oCo7d8asrNsGH6wuA+S8bs0D9catFUsns7keNly/kOizdtQ8ZVrfcxHAG86S9tTl7D7sWJAYxPi+BuOj8XkzS6f1kj98j4DJVZ99Td7WnTBjC6NsAvzQpc048C4YWY3JyfoFNt4fMZTM2mCQ2x3WUJYheYhXXaSGdDQe45BW/LtN2NATfy2fd15FHlN0L1HN3gEj9GqPwJSL2qrys5JBrOVazTmgZpsLw+0BAV9Dlpb4gJRKxLIANn6CNXnOXQjcog6E3jpVSuiVsYqvxjvD1i49sSi/C0ZnrtAv1EJqttcBJXUC91XfImekeiSJ8T28iuD4jOwNQyKF3/RHcBOYh0wTcOo1Umc4wg4I/Mhzxu9NcTIZ81nfnaFZayNCaMiihM9Hp6MrRU3TuVkFPI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
